/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.com.parchisdemo.view;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import ucr.com.parchisdemo.controller.GameController;

/**
 *
 * @author ITM
 */
public class BoardPanel extends javax.swing.JPanel {
  private ImageIcon tableroGrafico;
  private GameController controller;
    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
        tableroGrafico = new ImageIcon("./src/main/resources/img/tableroGrafico2.png");
    }
    
     public void setController(GameController controller) {
        this.controller = controller;
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
       // g.drawString("Esta es una prueba", 100, 100);
        tableroGrafico.paintIcon(this, g, 0, 0);
        if(controller!=null){
        controller.draw(this,g);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
