/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.com.parchisdemo.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import ucr.com.parchisdemo.controller.GameController;

/**
 *
 * @author ITM
 */
public class ControlPanel extends javax.swing.JPanel {

    private ImageIcon fondoJuego;
    private GameController controller;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        fondoJuego = new ImageIcon("./src/main/resources/img/TableroFondo.png");

    }

    public void setController(GameController controller) {
        this.controller = controller;
        listen();
    }

    public void listen() {
        btnDado.addActionListener(controller);
        btnExit.addActionListener(controller);
        btnPlay.addActionListener(controller);
    }

    public String getJlNamePlayer1() {
        return jlNamePlayer1.getText();
    }

    public void setJlNamePlayer1(String namePlayer1) {
        this.jlNamePlayer1.setText(namePlayer1);
    }

    public String getJlNamePlayer2() {
        return jlNamePlayer2.getText();
    }

    public void setJlNamePlayer2(String namePlayer2) {
        this.jlNamePlayer2.setText(namePlayer2);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        jlPlayer1 = new javax.swing.JLabel();
        jlPlayer2 = new javax.swing.JLabel();
        jlNamePlayer1 = new javax.swing.JLabel();
        jlNamePlayer2 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado1.png"))); // NOI18N
        btnDado.setActionCommand("dado");
        btnDado.setBorderPainted(false);
        btnDado.setContentAreaFilled(false);
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonSalir.png"))); // NOI18N
        btnExit.setActionCommand("exit");
        btnExit.setContentAreaFilled(false);
        add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 630, -1, -1));

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonJugar.png"))); // NOI18N
        btnPlay.setActionCommand("playGame");
        btnPlay.setContentAreaFilled(false);
        add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));

        jlPlayer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugador1.png"))); // NOI18N
        add(jlPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        jlPlayer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugador2.png"))); // NOI18N
        add(jlPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jlNamePlayer1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlNamePlayer1.setText("Jugador 1");
        add(jlNamePlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jlNamePlayer2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlNamePlayer2.setText("Jugador 2");
        add(jlNamePlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroFondo.png"))); // NOI18N
        add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlNamePlayer1;
    private javax.swing.JLabel jlNamePlayer2;
    private javax.swing.JLabel jlPlayer1;
    private javax.swing.JLabel jlPlayer2;
    // End of variables declaration//GEN-END:variables
}
