/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.com.parchisdemo.view;

import javax.swing.JOptionPane;
import ucr.com.parchisdemo.controller.GameController;

/**
 *
 * @author ITM
 */
public class GUIGame extends javax.swing.JFrame {

    /**
     * Creates new form GUIGame2
     */
    public GUIGame(GameController controller) {
        initComponents();
        boardPanel.setController(controller);
        controlPanel.setController(controller);
    }

    public BoardPanel getBoardPanel() {
        return boardPanel;
    }

    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null,message);
    }
    
    public String getMessage(String message){
        return JOptionPane.showInputDialog(message);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new ucr.com.parchisdemo.view.BoardPanel();
        controlPanel = new ucr.com.parchisdemo.view.ControlPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boardPanel.setOpaque(false);

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(boardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 620, 620));
        getContentPane().add(controlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.com.parchisdemo.view.BoardPanel boardPanel;
    private ucr.com.parchisdemo.view.ControlPanel controlPanel;
    // End of variables declaration//GEN-END:variables
}
