/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.com.parchisdemo.view;

import ucr.com.parchisdemo.controller.MainController;

/**
 *
 * @author ITM
 */
public class GUIMain extends javax.swing.JFrame {
   private MainController controller;
    /**
     * Creates new form GUIMain
     */
    public GUIMain(MainController controller) {
        initComponents();
        this.controller=controller;
        listen();
    }
    
    public void listen(){
    btnExit.addActionListener(controller);
    btnPlay.addActionListener(controller);
    btnInstructions.addActionListener(controller);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setText("Jugar");
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        btnInstructions.setText("Instrucciones");
        getContentPane().add(btnInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        btnExit.setText("Salir");
        btnExit.setToolTipText("");
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("Juguemos Parchis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
