/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.com.parchisdemo.view;

import ucr.com.parchisdemo.controller.MainController;

/**
 *
 * @author ITM
 */
public class GUIMain extends javax.swing.JFrame {
   private MainController controller;
    /**
     * Creates new form GUIMain
     */
    public GUIMain(MainController controller) {
        initComponents();
        this.controller=controller;
        listen();
    }
    
    public void listen(){
    btnExit.addActionListener(controller);
    btnPlay.addActionListener(controller);
    btnInstructions.addActionListener(controller);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSonido = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugarPrincipal.png"))); // NOI18N
        btnPlay.setActionCommand("Jugar");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 300, 80));

        btnInstructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instruccionesPrincipal.png"))); // NOI18N
        btnInstructions.setActionCommand("Instrucciones");
        btnInstructions.setBorderPainted(false);
        btnInstructions.setContentAreaFilled(false);
        getContentPane().add(btnInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonSalir.png"))); // NOI18N
        btnExit.setToolTipText("");
        btnExit.setActionCommand("Salir");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, -1, -1));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creditosPrincipal.png"))); // NOI18N
        btnCreditos.setActionCommand("Créditos");
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        btnSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sonido.png"))); // NOI18N
        btnSonido.setActionCommand("Sonido");
        btnSonido.setBorderPainted(false);
        btnSonido.setContentAreaFilled(false);
        getContentPane().add(btnSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 100, -1));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historiaPrincipal.png"))); // NOI18N
        btnHistoria.setActionCommand("Historia");
        btnHistoria.setBorderPainted(false);
        btnHistoria.setContentAreaFilled(false);
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSonido;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
