/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.com.parchisdemo.view;

import javax.swing.JComboBox;
import javax.swing.JTextField;
import ucr.com.parchisdemo.controller.GameController;
import ucr.com.parchisdemo.controller.MainController;

/**
 *
 * @author ITM
 */
public class OptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form OptionGUI
     */
    public OptionGUI(GameController controller) {
        initComponents();
        listen(controller);
    }

    
    public void listen(GameController controller){
       btnNext.addActionListener(controller);
    }
    public String getCbxColor() {
        return (String) cbxColor.getSelectedItem();
    }

    public String getTxtNamePlayer1() {
        return txtNamePlayer1.getText();
    }

    public String getTxtNamePlayer2() {
        return txtNamePlayer2.getText();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNamePlayer1 = new javax.swing.JTextField();
        txtNamePlayer2 = new javax.swing.JTextField();
        cbxColor = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamePlayer1.setColumns(20);
        getContentPane().add(txtNamePlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        txtNamePlayer2.setColumns(20);
        getContentPane().add(txtNamePlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonContinuar.png"))); // NOI18N
        btnNext.setActionCommand("Continuar");
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPersonaje.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNamePlayer1;
    private javax.swing.JTextField txtNamePlayer2;
    // End of variables declaration//GEN-END:variables
}
