/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.com.parchisdemo.view;

import javax.swing.JComboBox;
import javax.swing.JTextField;
import ucr.com.parchisdemo.controller.GameController;
import ucr.com.parchisdemo.controller.MainController;

/**
 *
 * @author ITM
 */
public class OptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form OptionGUI
     */
    public OptionGUI(GameController controller) {
        initComponents();
        listen(controller);
    }

    
    public void listen(GameController controller){
       btnNext.addActionListener(controller);
    }
    public String getCbxColor() {
        return (String) cbxColor.getSelectedItem();
    }

    public String getTxtNamePlayer1() {
        return txtNamePlayer1.getText();
    }

    public String getTxtNamePlayer2() {
        return txtNamePlayer2.getText();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamePlayer1 = new javax.swing.JTextField();
        txtNamePlayer2 = new javax.swing.JTextField();
        cbxColor = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Escoja su color");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre Jugador 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre jugador 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtNamePlayer1.setColumns(20);
        getContentPane().add(txtNamePlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        txtNamePlayer2.setColumns(20);
        getContentPane().add(txtNamePlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        btnNext.setText("Continuar");
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNamePlayer1;
    private javax.swing.JTextField txtNamePlayer2;
    // End of variables declaration//GEN-END:variables
}
